version: "3.8"

services:
  gcp-agent:
    image: ly920907/komari-agent:latest
    container_name: komari-agent
    restart: always
    network_mode: host     # 使用宿主机网络
    environment:
      AGENT_ENDPOINT: https://AGENT_ENDPOINT
      AGENT_TOKEN: 
      
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
